name: Deploy Little Explorer to AWS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-west-1
  ECR_REGISTRY: 339713127263.dkr.ecr.us-west-1.amazonaws.com
  ECR_REPOSITORY: little-explorer-repo
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: little-explorer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Setup AWS Credentials (GitHub runner)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 2. Login to ECR (GitHub runner)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Build and Push Image
      - name: Build, Tag, and Push Image to ECR
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          docker build \
            --build-arg VITE_API_URL=$VITE_API_URL \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 4. Deploy to EC2
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Logging into ECR..."
            aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 339713127263.dkr.ecr.us-west-1.amazonaws.com

            echo "Pulling latest image..."
            docker pull 339713127263.dkr.ecr.us-west-1.amazonaws.com/little-explorer-repo:latest

            echo "Stopping old container..."
            docker rm -f little-explorer || true

            echo "Starting new container..."
            docker run -d \
              --name little-explorer \
              -p 80:4000 \
              --restart always \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              339713127263.dkr.ecr.us-west-1.amazonaws.com/little-explorer-repo:latest

            echo "Running migrations..."
            docker run --rm \
                    --env DATABASE_URL="${{ secrets.DATABASE_URL }}" \
                    339713127263.dkr.ecr.us-west-1.amazonaws.com/little-explorer-repo:latest \
                    npx prisma migrate deploy